#' Struktura tabel wejsciowych
#' @description Funkcja zwraca listę zawierającą nazwy kolumn, które oczekiwane
#' są w poszczególnych plikach z tabelami wejściowymi.
#' @returns lista wektorów tekstowych
#' @export
tabele_wejsciowe <- function() {
  return(list(
    STYPSZK = c("TYP_SZK", "TYP_SZK_NAZWA"),
    W1 = c("ID_ABS", "ROK_ABS"),
    W2 = c("ID_ABS", "ROK_ABS", "ROK_UR", "PLEC", "ID_SZK", "KOD_ZAW", "NAZWA_ZAW", "TYP_SZK", "TERYT_SZK"),
    W3 = c("ID_ABS", "ROK_ABS", "ID_SZK_KONT", "DATA_OD_SZK_KONT", "CZY_UKONCZ_SZK_KONT", "DATA_DO_SZK_KONT", "KOD_ZAW_KONT", "TYP_SZK_KONT"),
    W4 = c("ID_ABS", "ROK_ABS", "ID_SZK_KONT", "DATA_OD_KKZ", "DATA_DO_KKZ", "KOD_KWAL_KKZ"),
    W5 = c("ID_ABS", "ROK_ABS", "ID_SZK_KONT", "DATA_OD_KUZ", "DATA_DO_KUZ", "KOD_ZAW_KUZ"),
    W6 = c("ID_ABS", "ROK_ABS", "KOD_ZAW_CZEL"),
    W7 = c("ID_ABS", "ROK_ABS", "ROK_MATURA", "CZY_ZDANA_MATURA", "DATA_SWIAD_MATURA"),
    W8 = c("ID_ABS", "ROK_ABS", "ROK_KWAL", "KOD_KWAL", "DOK_POTW_KWAL", "DATA_KWAL"),
    W9 = c("ID_ABS", "ROK_ABS", "ROK_DYP", "DOK_POTW_DYP", "DATA_DYP_ZAW", "KOD_ZAW"),
    W10 = c("ID_ABS", "ROK_ABS", "ROK_KWAL", "KOD_KWAL", "DOK_POTW_KWAL", "DATA_KWAL"),
    W11 = c("ID_ABS", "ROK_ABS", "ROK_DYP", "DOK_POTW_DYP", "DATA_DYP_ZAW", "KOD_ZAW"),
    W12 = c("ID_ABS", "ROK_ABS", "ID_KIERUNKU_STU", "KIERUNEK_STU", "PROFIL_STU", "DATA_OD_STU", "CZY_UKONCZ_STU", "DATA_DO_STU", "TYTUL_ZAW_STU", "DATA_SKRESL_STU"),
    W13 = c("ID_KIERUNKU_STU", "DZIEDZINA", "DYSCYPLINA", "CZY_DYSCYPLINA_WIODACA"),
    W14 = c("ID_ABS", "ROK_ABS", "ROK_ZGONU", "MIES_ZGONU"),
    W15 = c("ID_ABS", "ROK_ABS", "ADRES_TYP", "DATA_ADR_OD", "DATA_ADR_DO", "TERYT"),
    W16 = c("ID_ABS", "ROK_ABS", "ID_PLATNIKA", "OKRES_ROZL", "KOD_ZUS", "PODST_CHOR", "PODST_WYPAD", "PODST_EMER", "PODST_ZDROW", "CZY_30", "CZY_RSA"),
    W17 = c("ID_ABS", "ROK_ABS", "ID_PLATNIKA", "KOD_PRZERWY", "DATA_OD_PRZERWA", "DATA_DO_PRZERWA"),
    W18 = c("ID_PLATNIKA", "PKD", "ROK_WYREJ", "MIES_WYREJ"),
    W19 = c("ROK", "MIESIAC", "TERYT", "STOPA_BEZROBOCIA", "SR_WYNAGRODZENIA"),
    W20 = c("KOD_ZAW", "BRANZA", "BRANZA_KOD"),
    W20aneks = c("KOD_ZAW", "BRANZA", "BRANZA_KOD"),
    W21 = c("KOD_KWAL", "KOD_ZAW"),
    W22 = c("KOD", "OPIS", "ETAT_ELA", "ETAT_IBE", "SKLADKA_SZAC_WYNAG", "NETAT_IBE", "BIERNY_SKLADKA", "NETAT_ELA", "ZLEC_ELA", "BEZROB_ELA", "STUDENT_ELA", "ZAGRANIC_ELA", "PRAWNIK_ELA", "SAMOZ_ELA", "NSPRAW_ELA", "ROLNIK_ELA", "RENTEMER_ELA", "MUNDUR_ELA", "DZIECKO", "ETATNOKID", "NETATNOKID_ELA", "SAMOZNOKID_ELA", "INNE_ELA", "MACIERZYNSKI_ELA", "DZIECKO_PRACOWNIK_ELA", "DZIECKO_SAMOZATRUDNIENIE_ELA", "DZIECKO_ZLECENIE_ELA", "DZIECKO_BEZPRACY_ELA", "WYCHOWAWCZY_OPIEKA", "MLODOC", "BENEPOMSPOL", "BEZROBOTNYSTAZ",
            "BEZROB_IBE", "INNE_IBE", # dodane w 2022 r.
            "POMOC_SPOL", "MACIERZ", "WYCHOW"), # dodane w 2023 r.
    W23 = c("KOD", "OPIS", "BIERNY_ZAWODOWO",
            "DZIECKO2", "WYPADEK", "CHOROBA", "CHOROBA_MACIERZ"), # dodane w 2023 r.
    W24 = c("KOD_ZAW", "KOD_ISCED", "GRUPA_ISCED", "PODGRUPA_ISCED", "NAZWA_ISCED"), # dodane w 2023 r.
    W25 = c("TERYT_POW", "POWIAT", "WOJEWODZTWO", "NTS", "MAKROREGION", "REGION", "PODREGION") # dodane w 2023 r.
  ))
}
